files:
  - source: /_data/i18n.yml
    translation: /%original_path%/%file_name%.%two_letters_code%.yml
  - source: /**/*.md
    ignore:
      - /**/*.*.md
    translation: /**/%file_name%.%two_letters_code%.md
  - source: /**/*.html
    translation: /**/%file_name%.%two_letters_code%.html
